spring.application.name=trading
spring.datasource.url=jdbc:postgresql://localhost:5432/jrvstrading
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration de l'API Alpha Vantage via Rapid API
alpha.vantage.host=https://alpha-vantage.p.rapidapi.com
alpha.vantage.token=97a17ce634msh9054341c3c37c6cp15ddb9jsn41edd7e0ae7c

