!/bin/bash

FROM postgres:9.6-alpine

# Add the schema.sql file to the initialization directory
COPY /Users/laminedjobo/JDBC/springboot/SpringBoot/src/main/resources/schema.sql /docker-entrypoint-initdb.d/


